travis:
  secure:
    BINSTAR_TOKEN: PTuGUZp5BW3mzVQKNiihf5U6vjSyLXnLJMAV3f0uEdtWpAryfYMu3PJ0DkcgrTxM6tIo7SXtB9xXtyZcVop2UgOpeD9lmskKqpP46ArktIjyu4SIyqO3yVpG6zp5pWWrGfK90Nlbe0gEDchxuY0CB3KuX9eHvMikPz2FuvjjS3uw49FoAVSk5dqRaw8B4H3cGBcWMi8yuVfW3M8B9YbwLZtJfw/Q+I/dibhD6dXAWS4v6wCTtKwvkvjAr6f5lH6EGWwxXEP7EKMvOKpPBh6FEd/dT0t2awZNGnYWJzZnCvbooDYDnOeIiG1F/VNTbeW5hKVhEi5C4XpCxA/9dO4Xz+InnDlMkWgNVnT8FEouryZwCsnVeZeOsYtW62sXJ2gHTXvVGzgAgCjMU+AqUarQwCJb5a9bClbcgQE+l5aAuXBVzOGt9qoMietfSqR43fgdNwtqsRZteGFQpQJWaMCu+eIyLEvIPWyqsOVMK2Xr8dA9SjfSjpF/7kDltU3KurRqZCOpuKcf8vzD2U52Oi3RxFwi4koPxRSUoJVAFNJHGJfaLgXop/T9vmrQRoJsSJv1WciS/RlsnIn1aDnkokZJapxqU9E+Phl9GR2U5m3gq1/xpi4Gy5xvJGQ4NZ7ggxRaBqPDhfqHzy5hRrdabHDkblkKuyhWJPDBtbcedUKc4S4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
